DROP TABLE IF EXISTS resources CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE resources (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    about TEXT NOT NULL,
    website TEXT,
    logo TEXT
);

CREATE TABLE tags (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    resourceid BIGINT NOT NULL REFERENCES resources(id),
    tag TEXT
);

CREATE TABLE locations (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    resourceid BIGINT NOT NULL REFERENCES resources(id),
    located TEXT
);